# -*- coding: utf-8 -*-
{
    'name': "IAC Report",
    'summary': """
        IAC Report
        """,
    'description': """
        英华达報表模块
    """,
    'author': "Ning",
    'website': "www.iac.com",
    "category" : "IAC",
    'version': '10.0.0.1',
    'depends': [
        'base', 'warning_box', 'oscg_vendor','iac_vendor_evaluation', 'oscg_rfq', 'oscg_interface',
    'oscg_control_table', 'iac_forecast_release_to_vendor'
    ],
    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        # 'security/ir_security.xml',
        'view/sop_attachment.xml',  # 20180604 laura add
        'view/List_RFQ_History.xml',
        'view/Max_QTY_allowed_for_ASN.xml',
        'view/po_unconfirm_detail.xml',
        'view/po_cancel_history.xml',
        'view/Vendor_Copy_History_Report.xml',
        'view/Purchase_Group_List.xml',
        'view/Vendor_Change_History.xml',
        'view/vendor_vs_buyer_email.xml',
        'view/po_change_payment.xml',
        'view/supplier_exception_monitor_views.xml',
        'view/PO_unconfirm_summary.xml',
        'view/po_price_change_history.xml',
        'view/Vendor_Report.xml',
        'view/Payment_Term_Change_Log.xml', #by pw
        'view/Bulletin_Information_Report.xml',
        # 'view/Vendor_History_Record_Query.xml',
        # 'view/Review_List_Record_Query.xml',
        # 'view/Supplier_Rating_State_Query.xml',
        # 'view/Download_Fractional_Detail_Report.xml',
        'view/Email_Alert_Report.xml',
        # 'view/Uncompleted_Form_Query.xml',
        # 'view/Portal_SOP.xml',
        'view/RFQ_Price_Difference_Table.xml',
        'view/ASN_Report.xml',
        'view/ASN_report_for_subcontractor.xml',
        'view/InTransit_ASN_Price_Change_Report.xml',
        'view/Transverse_PO_Data.xml',
        'view/New_PO_Without_Vendor_Confirm.xml',
        'view/PO_Report.xml',
        'view/PO_Report_qweb_header.xml',
        'view/PO_Report_qweb_template.xml',
        'view/PO_Report_for_LG.xml',
        'view/PO_Report_for_LG_qweb_header.xml',
        'view/PO_Report_for_LG_qweb_template.xml',
        # 'view/Po_Price_VS_Rfq.xml',
        'view/Open_Po_VS_Rfq.xml',
        'view/Comparison_Report.xml',
        'view/Payment_Info.xml',
        'view/Global_Vendor_Report_QM.xml',
        'view/Global_Vendor_Report.xml',
        'view/PO_Delete_State.xml',
        # 'view/Registration_Doc.xml',
        'view/Supplier_Attachment_List.xml',
        'view/Vendor_Evaluation_Detail.xml',
        'view/Vendor_Evaluation_Summary.xml',
        'view/Vendor_Evaluation_Approval_Log.xml',
        'view/Vendor_Dclass_Approval_Log.xml',
        'view/vendor_without_gv_code_report.xml',
        'view/po_buyer_code_change_log.xml',
        'view/Inforecord_cross_up_report.xml',
        'view/RFQ_uploadlist_as.xml',
        'view/RFQ_uploadlist_MM.xml',
        'view/Rfq_list_search.xml',
        'view/RFQ_quota_audit_report.xml',
        # 'view/Inforecord_cross_plant_exception.xml',
        'view/location_address_manage.xml',
        'view/asn_without_declare_data.xml',
        'view/Supplier_Utilization_Statement.xml',
        'view/customs_pass_port_list.xml',
        'view/customs_pass_port_list_qweb_header.xml',
        'view/customs_pass_port_list_qweb_template.xml',
        'view/iac_asn_customs_sas_report.xml',
        'view/SAS_Report_for_buyer_lg_header.xml',
        'view/SAS_Report_qweb_template.xml',
        'view/menu.xml',
    ],
    'demo': [
        # 'demo/demo.xml',
    ],
	'images': ['static/description/icon.png'],
    'installable': True,
    'application': True
}