{

	"flow_id": [],
	"request_id": "21203471",
	"data": {
		"destination": "Hong Kong",
		"address_pobox": "",
		"bank_street": "Kaiserstrabe 66-68, 63065 , Germany",
		"bank_branch_name": "Offenbach am Main",
		"currency": "USD",
		"vat_number": "",
		"vendor_regist_id": "1500",
		"address_street": "Rm A2-A3, 5/F Wing Tai Centre,12 Hi",
		"id": "1500",
		"sales_email": "phoenixy@chip1.com",
		"address_postalcode": "63263",
		"address_country": "Germany",
		"payment_term": "OA30",
		"address_district": "Kowloon, Hong Kong",
		"sales_telephone": "+00852-25719937",
		"swift_code": "DEUTDEFF505",
		"local_or_foreign": "foreign",
		"bank_name": "Deutsche Bank AG",
		"plant": "浦東廠(英華達(上海)科技)",
		"company_telephone2": "",
		"name2_en": "",
		"short_name": "Chip1 Exch",
		"company_telephone1": "+00852-25719937",
		"buyer_email": "wang.yuki@iac.com.tw",
		"bank_city": "Offenbach am Main",
		"company_fax": "+49-06102-8169-105",
		"name2_cn": "",
		"incoterm": "EXW",
		"address_city": "Kwun Tong",
		"transfer_number": "",
		"name1_en": "Chip 1 Exchange GmbH & Co. KG",
		"name1_cn": "Chip 1 Exchange GmbH & Co. KG",
		"bank_country_code": "Germany",
		"account_number": "03385010 01",
		"sales_person": "Phoenix Yung"
	},
	"inf_call_id": 10365644,
	"stage": "F05_B"
}